[khan_sungsooh]
title = "경향신문 ─ 홍성수의 물구나무"
url = "https://www.khan.co.kr/series/articles/ao376"
entrySelector = "ul.df-list li"
titleSelector = "h2.tit a"
linkSelector = "div h2 a"
dateSelector = "span.byline"
contentSelector = "a.line_clamp2"
waitUntil = "networkidle"

[ohmynews_mongsill]
title = "오마이뉴스 ─ 신필규 시민기자"
url = "http://star.ohmynews.com/NWS_Web/Mobile/i_Room/articles/news_list.aspx?MEM_CD=00701855"
entrySelector = "ul.newest_list li"
titleSelector = "strong.title"
linkSelector = "div.newest_area a.link_today"
contentSelector = "div.category"
imageSelector = "div.image_area img"
waitUntil = "networkidle"

[dongascience_parkjy]
title = "동아사이언스 ─ 박진영 심리학 칼럼니스트"
url = "https://www.dongascience.com/journalist.php?email=parkjy0217%40gmail.com"
entrySelector = "div.article-A2 ul li"
titleSelector = "dd span.tit"
linkSelector = "a"
contentSelector = "span.cont"
waitUntil = "networkidle"

[naver_dongascience_parkjy]
title = "네이버 뉴스 ─ 동아사이언스 ─ 박진영의 사회심리학"
url = "https://news.naver.com/main/hotissue/sectionList.naver?mid=hot&sid1=110&cid=1077376"
entrySelector = "ul.tmp_bx li.tmp.small2"
titleSelector = "dl.cnt dt.t a"
linkSelector = "dl > dt > a"
contentSelector = "dd.c"
imageSelector = "div.thumb a img"
waitUntil = "networkidle"

[daum_dongascience_parkjy]
title = "다음 뉴스 ─ 동아사이언스 ─ 박진영의 사회심리학"
url = "https://news.daum.net/series/943444"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_khan_sungsooh]
title = "다음 뉴스 ─ 경향신문 ─ 홍성수의 물구나무"
url = "https://news.daum.net/series/5190096"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_thumb"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_khan_quarterlyalone]
title = "다음 뉴스 ─ 경향신문 ─ 이진송의 아니 근데"
url = "https://news.daum.net/series/5140981"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_thumb"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_hani_tintin]
title = "다음 뉴스 ─ 한겨레S ─ 이승한의 술탄 오브 더 티브이"
url = "https://entertain.daum.net/news/series/3306"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_thumb"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[daum_khan_plusratioquamvis]
title = "다음 뉴스 ─ 경향신문 ─ 위근우의 리플레이"
url = "https://news.daum.net/series/5024350"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a.link_thumb"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"
